version: '3'
services:

    jenkins:
      build: ./.docker/
      # Naming our image
      image: jenkins_enhanced:lts-jdk17
      container_name: jenkins-jdk8-jdk11-jdk17
      network_mode: bridge
      restart: always
      ports:
        - '127.0.0.1:8085:8080'
      runtime: sysbox-runc
      volumes:
        - ./volumes/jenkins-data:/var/jenkins_home
        - ./volumes/jenkins-certs:/certs/client:ro

